### PR TITLE
Fix high CPU usage on Linux due to epoll busy-loop

### LINKED ISSUE #186: high CPU usage in FlyingSocks
Still investigating this, potentially I am ’holding it wrong’. We are seeing this on Linux in [OpenSRP](https://github.com/PADL/OpenSRP), which uses FlyingFox to host a REST server for monitoring. `perf` data is below, I'm retesting with debug symbols now, just need to wait for the issue to recur.

Image

cc @nippoo @ideoforms

### PR DESCRIPTION
**Pull request by lhoward**
NB: these fixes were generated by AmpCode. They appear to fix the issue and also do not break tests.

—

Three fixes for 100% CPU spinning when HTTPServer is idle on Linux:

1. Use edge-triggered (EPOLLET) mode for all sockets, not just the canary eventfd. Level-triggered epoll causes epoll_wait() to return immediately when the listening socket is readable, creating a busy loop.

2. Change accept() to wait on .read events only instead of .connection ([.read, .write]). A listening socket is always writable (EPOLLOUT), so registering for write events causes immediate spurious wakeups. accept() only needs readability (a pending connection).

3. Skip redundant epoll_ctl(EPOLL_CTL_MOD) calls when the event mask hasn't changed. EPOLL_CTL_MOD re-arms edge-triggered events and can cause spurious wakeups when the condition is already met.

Fixes: #186

### CODE REVIEW

**Comment by lhoward** [comment]
@swhitty just pinging on this :)

File: FlyingSocks/Sources/AsyncSocket.swift [hunk 1]
```diff
@@ -131,7 +131,7 @@ public struct AsyncSocket: Sendable {
 
     @Sendable
     public func accept() async throws -> AsyncSocket {
-        try await pool.loopUntilReady(for: .connection, on: socket) {
+        try await pool.loopUntilReady(for: .read, on: socket) {
```
Comment (swhitty) [inline FlyingSocks/Sources/AsyncSocket.swift]: could we localise this change to just linux for now — I remember I needed write events for iOS disconnection detection so I'll need to look into that

```swift
#if canImport(Glibc)
static let connection: Self = [.read]
#else
static let connection: Self = [.read, .write]
#endif
```

File: FlyingSocks/Sources/SocketPool+ePoll.swift [hunk 2]
```diff
@@ -105,6 +105,7 @@ public struct ePoll: EventQueue {
     }
 
     mutating func setEvents(_ events: Socket.Events, for socket: Socket.FileDescriptor) throws {
+        if existing[socket] == events { return }
```
Comment (swhitty) [inline FlyingSocks/Sources/SocketPool+ePoll.swift]:
```suggestion
        guard existing[socket] != events else { return }
```

File: FlyingSocks/Sources/SocketPool+ePoll.swift [hunk 3]
```diff
@@ -242,7 +243,9 @@ private struct EPOLLEvents: OptionSet, Hashable {
 private extension Socket.Events {
 
     var epollEvents: EPOLLEvents {
-        reduce(EPOLLEvents()) { [$0, $1.epollEvent] }
+        var events = reduce(EPOLLEvents()) { [$0, $1.epollEvent] }
+        events.insert(.edgeTriggered)
```
Comment (swhitty) [inline FlyingSocks/Sources/SocketPool+ePoll.swift]: Would it be possible to pass this as an option to `structure ePoll` so users can revert to level triggered events if they need to?

```
let pool = SocketPool<ePoll>(triggering: .edge, maxEvents: ....)
let socket = AsyncSocket(pool: pool)
```

I don't mind if the default changes to `.edge`, just a way to easily go back if there is an issue

**Comment by swhitty** [comment]
Thanks for this Luke, just a couple of changes to provide a way to revert the changes at runtime if we need

**Comment by swhitty** [comment]
also, is there an easy way I can reproduce this issue on Linux with FlyingFoxCLI?

I've tried in docker / container and it isn't looping when waiting for connections, do I need to use a VM?

**Comment by lhoward** [comment]
> also, is there an easy way I can reproduce this issue on Linux with FlyingFoxCLI?
> 
> I've tried in docker / container and it isn't looping when waiting for connections, do I need to use a VM?

I was only able to reproduce it with my code but, I'll try get Claude or Amp to make a repro case.

**Review by swhitty — APPROVED** [review]
